### ISSUE TITLE
Blank/Silent sound in between happening ocasionally

### ISSUE THREAD

**Issue by jugaldesai** [VladimirKravchenko/AVAudioEngineOfflineRender#5]
Many people had issues with a blank/silent sound appearing in between after rendering the audio discussed [here](http://stackoverflow.com/questions/30679061/can-i-use-avaudioengine-to-read-from-a-file-process-with-an-audio-unit-and-writ).

@VladimirKravchenko you gave a solution at [stackoverflow](http://chat.stackoverflow.com/rooms/80197/discussion-between-greg-and-vladimir-kravchenko) to use
`AVAudioFramePosition lengthInFrames = duration * audioDescription->mSampleRate;` on line number 107.

However, both the solutions did not work for me. The blank/silent audio various many a times it is long and sometimes it is short. No sign of constant behaviour.

**Comment by jugaldesai** [comment]
I found the root cause of the problem. When my **duration** is constant for example 15.0000... this code works perfectly. 

When my duration is not a whole number for example 15.000090702947846 because I am recording the audio, I get a blank in between.

`lengthInFrames = 15.000090702947846 * 44100  // Generates 661504`

The value of lengthInFrames is 661504 instead it should be 661500. With the difference of 4, it generates a break in between the audio. The higher the difference the longer break in the sound.

It should also be noted that the break does not affect the continuity. After the break, it starts from exactly where it had stopped but the later part of the audio gets trimmed (the same size as that of the blank audio).

According to my observations, I feel that it has something to do with the buffer. Ending buffer is getting appended in the middle.

**Comment by masaldana2** [comment]
what's the solution bro?

**Comment by jugaldesai** [comment]
The library works perfectly. It was my bad. I tried various things and later on the final solution to the problem was kind of silly with AVAudioSession.
If the AVAudioSession is not started and terminated properly it generates an audio gap in-between. 

For example, I started recording the audio but the AVAudioSession was called after starting the session. Also, please check if you're using proper AVAudioSession while recording audio.

Another thing is to make sure these are Properties and strong

```
@property (strong, nonatomic) AVAudioPlayer *audioPlayer;
@property (strong, nonatomic) AVAudioRecorder *audioRecorder;
```
```
[[AVAudioSession sharedInstance] setCategory:AVAudioSessionCategoryPlayAndRecord error:&error];
    if(error){
        NSLog(@"ERROR: %@", error);
    }
    
    [[AVAudioSession sharedInstance] setActive:YES error:nil];
    
    // Initiate and prepare the recorder
    self.audioRecorder = [[AVAudioRecorder alloc] initWithURL:recordedAudioUrl settings:recordSetting error:NULL];
    self.audioRecorder.delegate = self;
    [self.audioRecorder prepareToRecord];
    
    [self.audioRecorder recordForDuration:seconds];
```

**Comment by masaldana2** [comment]
Hey, thanks for the quick response. I'm just getting silence and the length of the audio file as an output. im not recording audio.. just playing, I changed the properties to stong

**Comment by jugaldesai** [comment]
Sure, I can help you with the issue you're facing. Have you posted this question on StackOverflow already? The above issue pertains to AudioRecording it is better to have another question with your code too. It will help others who face the same issue. Thanks.

**Comment by masaldana2** [comment]
I'm just running this code out of the box, with no modifications and the question was asked here :)
https://github.com/VladimirKravchenko/AVAudioEngineOfflineRender/issues/3
but no solution yet

**Comment by jugaldesai** [comment]
I hope I got the picture. To rephrase your question, you have already recorded the audio using AVAudioRecorder and now playing the audio. The playing of audio is having a blank sound. Does this sound ok?

**Comment by masaldana2** [comment]
No, this project uses the included audio file 'jubel.m4a' a saxophone melody and then renders it :) there's no AVAudioRecorder, I posted here because maybe you went through that problem. The problem is complete silence of the output m4a.

**Comment by jugaldesai** [comment]
Okay. Sorry, I miss understood completely. Are you using the audio engine to generate the file correct?
Actually, for the output file was generated but it was not completely blank it had some delay only in the start.

**Comment by masaldana2** [comment]
yeah im using avaudioengine to render to the output m4a. 
so jubel.m4a(the included file) should be the same as output m4a

**Comment by jugaldesai** [comment]
Can you post your code for Audio Engine so that I can look into it? It would be better than just talking over the air.

**Comment by masaldana2** [comment]
is identical as:
i just downloaded the project and run it
https://github.com/VladimirKravchenko/AVAudioEngineOfflineRender/blob/master/AVAudioEngineOfflineRender/ViewController.m

**Comment by jugaldesai** [comment]
Did you try running this sample code and is it working for you?
Two issues which I think:
1. There are many instances of people reporting issue with simulator (if the sample code is not working)
2. Something buggy is there in code (if the sample code is working for you)

**Comment by masaldana2** [comment]
the sample code is not working for me and  i used the simulator and the ipad and it does not work with both :(

**Comment by jugaldesai** [comment]
I just tested the code works perfectly fine for me. Tested on iPhone 6.

**Comment by masaldana2** [comment]
Thats weird!! it works on my iphone 6 too but not simulator or ipad pro.

Thanks bro1:)

**Comment by jugaldesai** [comment]
Good to hear that. Please post if you find a solution to this. Thanks.

**Comment by aboelbisher** [comment]
HI 
the code works perfectly on iphone 6 and 6+ , but on iphone 7 and 7+ (talking about real devices not simulators)  it gives an output of silence , whats the problem ?
